# Generated by Django 5.2.3 on 2025-07-31 10:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sso", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
